apiVersion: v1
kind: Secret
metadata:
  name: {{ include "user-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.database.user }}
  DB_PASSWORD: {{ .Values.database.password }}